server:
  port: 8083

spring:
  application:
    name: product-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce
      username: admin
      password: adminpassword
      authentication-database: admin
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.*"
        spring.json.add.type.headers: false

logging:
  level:
    com.ecommerce.product: DEBUG 